apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: togglemaster
  labels:
    app: targeting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting
          image: 940104439733.dkr.ecr.sa-east-1.amazonaws.com/togglemaster/targeting:v1.0.0-ef238735c1e549dc279acf50a537c9c9ba6ffdbb
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: targeting-db-secret
                  key: database_url
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.togglemaster.svc.cluster.local:80"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi